name: TriggerItem
version: '1.0'
main: rccommand.trigger_item
api-version: 1.16
authors: [ Siliwolf ]
commands:
  create_trigger:
    description: Make a trigger item.
    usage: /create_trigger <COOLDOWN> <COMMAND WITHOUT SLASH>